#!/bin/bash
way=$(dirname "$0")
echo "pwd directory: ${way}"
if [ -e ${way}/server.properties ]; then
    echo -e "\033[32mserver.properties found\033[0m"
    if [ -e ${way}/eula.txt ]; then
        echo -e "\033[32meula.txt found\033[0m"
        if [ -e ${way}/world/level.dat ]; then 
            echo -e "\033[32mworld/level.dat found\033[0m"
            echo "starting backup..."
            mkdir -p ${way}/swap/world/dimensions/
            cp -rf ${way}/world/level.dat ${way}/world/data ${way}/world/datapacks ${way}/world/players ${way}/swap/world/
            x_meta=(-2 -1 0 1 2)
            y_meta=(-2 -1 0 1 2)
            folder_all=("region" "entities" "poi")
            get_list=${way}/world/dimensions
            spacename=($(ls ${way}/world/dimensions/))
            for spacename_sel in ${spacename[@]}; do
                dimension=($(ls ${way}/world/dimensions/${spacename_sel}/))
                for dimension_sel in ${dimension[@]}; do
                    cp -rf ${way}/world/dimensions/${spacename_sel}/${dimension_sel}/data ${way}/swap/world/dimensions/${spacename_sel}/${dimension_sel}/
                    for folder_sel in ${folder_all[@]}; do
                        mkdir -p ${way}/swap/world/dimensions/${spacename_sel}/${dimension_sel}/${folder_sel}/
                        for x_meta_sel in ${x_meta[@]}; do
                            for y_meta_sel in ${y_meta[@]}; do
                                if [ -e ${way}/world/dimensions/${spacename_sel}/${dimension_sel}/${folder_sel}/r.${x_meta_sel}.${y_meta_sel}.mca ]
                                then
                                    cp -f ${way}/world/dimensions/${spacename_sel}/${dimension_sel}/${folder_sel}/r.${x_meta_sel}.${y_meta_sel}.mca ${way}/swap/world/dimensions/${spacename_sel}/${dimension_sel}/${folder_sel}/
                                else
                                    echo -e "\033[33m${spacename_sel}/${dimension_sel}/${folder_sel}/r.${x_meta_sel}.${y_meta_sel}.mca not found,skip this file\033[0m"
                                fi
                            done
                        done
                    done
                done
            done
            date=$(date +%y.%m.%d)
            if [ -e saves -a -d saves ]; then
                echo "saves exists, skip create this file"
            else
                mkdir saves
            fi
            cd ./swap/
            zip -r ../saves/backup-${date}.zip world/
        else
            echo -e "\033[31mworld/level.dat not found\033[0m"
        fi
    else
        echo -e "\033[31meula.txt not found\033[0m"
    fi
else
    echo -e "\033[31mserver.properties not found\033[0m]"
fi
#